---
- name: Deploy With Ansible
  hosts: localhost
  connection: local
  become: yes

  tasks:
    - name: Bau
      debug:
        msg: bau

    - name: update
      apt:
        name: nano
        state: present

    # Download an artifact from a private repository requiring authentication
    - maven_artifact:
        group_id: it.hackubau
        artifact_id: hackubau-docs
        repository_url: 'http://localhost:8081/repository/maven-releases/repository/it.hackubau/hackubau-docs-1.0-RELEASE/1/hackubau-docs-1.0-RELEASE-1.jar'
        username: admin
        password: qqQQ11!!
        dest: /tmp/bau.jar