---
- name: Deploy With Ansible
  hosts: localhost
  connection: local
  become: yes

  tasks:
    - name: Bau
      debug:
        msg: bau

    - name: update
      apt:
        name: python-lxml
        state: present

    # Download an artifact from a private repository requiring authentication
    - maven_artifact:
        group_id: it.hackubau
        artifact_id: hackubau-docs
        version: "1"
        #repository_url: 'http://localhost:8081/repository/maven-releases/repository/hck'
        repository_url: "http://{{ lookup('env','NEXUS_URL') }}/repository/maven-releases/repository/hck"
        username: admin
        password: qqQQ11!!
        dest: /tmp/bau.jar